title: Voltage glitching on STM32F4 MCUs
description: Bypassing Read Protection to extract firmware from STM32 Microcontrollers.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
author: Jerin Sunny, Shakir Zari

owner : Jerin Sunny
year: 2024
date: 10-04-2024