title: Voltage glitching on STM32F4 MCUs
tagline : Voltage glitching on STM32F4 MCUs
description: Bypassing Read Protection to extract firmware from STM32 Microcontrollers.
show_downloads: false
google_analytics: G-DW62RVHCXG
theme: jekyll-theme-hacker
author:
  name: Jerin Sunny

author1: Jerin Sunny
author2: Shakir Zari
author1_profile_pic: https://avatars.githubusercontent.com/u/166545686
author1_profile_link : https://www.linkedin.com/in/jerin-sunny/

author2_profile_pic: https://avatars.githubusercontent.com/u/166615503
author2_profile_link : https://www.linkedin.com/in/shakir-zari/ 

image : ./assets/images/banner.webp


owner : Jerin Sunny
year: 2024
date: 10-04-2024

twitter:
  title: Voltage glitching on STM32F4 MCU
  card: summary_large_image
